# Generated by Django 6.0.6 on 2026-07-08 03:48

from django.db import migrations

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('recluitment', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO usuario (username, password, nombre, telefono, correo)
            SELECT 'shawdog', 'pbkdf2_sha256$1200000$Okg6cOJr9FRpvrJtkwM7PL$ZSMKTthy/5kT/THVq986v/H9E3u1iifFUEHV0rXjVvM=', 'Admin', '0000000000', 'admin@example.com'
            WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE username = 'shawdog');

            INSERT INTO rol (descripcion)
            SELECT 'ROLE_RECLUTADOR' WHERE NOT EXISTS (SELECT 1 FROM rol WHERE descripcion = 'ROLE_RECLUTADOR');
            
            INSERT INTO rol (descripcion)
            SELECT 'ROLE_ASPIRANTE' WHERE NOT EXISTS (SELECT 1 FROM rol WHERE descripcion = 'ROLE_ASPIRANTE');
            
            INSERT INTO rol (descripcion)
            SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM rol WHERE descripcion = 'ROLE_ADMIN');

            INSERT INTO usuario_rol (usuario_id, rol_id)
            SELECT u.id, r.id 
            FROM usuario u, rol r 
            WHERE u.username = 'shawdog' AND r.descripcion IN ('ROLE_RECLUTADOR', 'ROLE_ASPIRANTE', 'ROLE_ADMIN')
            AND NOT EXISTS (
                SELECT 1 FROM usuario_rol ur WHERE ur.usuario_id = u.id AND ur.rol_id = r.id
            );
            """,
            reverse_sql="""
            DELETE FROM usuario_rol WHERE usuario_id IN (SELECT id FROM usuario WHERE username = 'shawdog');
            DELETE FROM usuario WHERE username = 'shawdog';
            """
        )
    ]