# Generated by Django 6.0.6 on 2026-07-08 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('type', models.CharField(choices=[('email_verification', 'Verificación de correo'), ('password_change', 'Cambio de contraseña')], max_length=20, verbose_name='Tipo de token')),
                ('is_used', models.BooleanField(default=False, verbose_name='¿Usado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de verificación',
                'verbose_name_plural': 'Tokens de verificación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code', 'type', 'is_used'], name='auth2fa_ver_user_id_26d048_idx')],
            },
        ),
    ]
